### ISSUE TITLE
Broken readme link

### ISSUE THREAD

**Issue by rejus-b** [Sandpaperr/Sandpaperr#1]
Hello, Sandpaperr,

I am here to tell your readme link is broken, here is how to do it for folders:

``` [-Text-](-URL-)```

As seen below for Unit 2:

```[Unit 2](https://github.com/Sandpaperr/Sandpaperr/tree/main/unit2)```

[Unit 2](https://github.com/Sandpaperr/Sandpaperr/tree/main/unit2)

**Comment by Sandpaperr** [comment]
Hi rejus-b, 
thanks for your support. The issue has now been fixed. 

Kind regards,
Sandpaperr
